### ISSUE TITLE
Formula explanation needed

### ISSUE THREAD

**Issue by Coernel82** [McOrts/Water_flow_sensor_MQTT#3]
Thank you for your sketch which was very helpful for me. However I struggle with this line of code:
https://github.com/McOrts/Water_flow_sensor_MQTT/blob/e2ff63b4e40b1be5027f534ec72069f5297ab740/Water_flow_sensor_MQTT.ino#L124
Where does this crazy number 2815562 come from?

My flow rate sensor's formula is: ```F = 7.5 + Q - 4```

When just changing your 6.6 to my 7.5 the values do not make sense yet. For a first step I would like to understand how you came up with your formula. When I resolve my formula for Q - that should be your ```CountLitre``` I come up with ```Q = (2+(F + 4))/15)```

Thank you for your help!

**Comment by nlooije** [comment]
I also don't understand the formula.
As mentioned in the README, each pulse is approximately 2.25 mL = 2.25/1000 L.
If your script counts the number of pulses `countFlow` in a time `update_time_sensors` then the total flow in mL in that time; `countFlow * 2.25`. 
Converting to an average flowrate in mL/ms: `countFlow * 2.25 / update_time_sensors`
Using a conversion factor for mL -> L: `countFlow * 2.25/1000 / update_time_sensors`
Using a conversion factor for ms -> min: `countFlow * 2.25/1000 * 60000/update_time_sensors`
or am I missing something?

**Comment by Coernel82** [comment]
As I didn't need an exact flow but had to find out after which flow rate my well drained I just made the formula very simple and adopted the threshold till I reached the perfect result. For filling my cistern I don't need to know the flowrate in litres but just if my well drains or not.
So problem solved!

**Comment by nlooije** [comment]
My formula wasn't giving me satisfactory results.
I check out this [tutorial](https://www.circuits-diy.com/water-flow-sensor-yf-s201-arduino-interface/#Arduino_Code_for_Water_Flow_Meter) which indicated the flowrate is the pulse frequency divided by 7.5.
I had to multiply with a calibration factor of 1.24 inorder to get same values as a reference meter i had installed.
So in the end my formula is simply `flow_rate = flow_frequency / 7.5 / period * 1.24;` where period is the time between measurements.
